### PR TITLE
Add ava test runner

### PR DESCRIPTION
**Pull request by degrammer**
- Add support for AVA Test runner (https://github.com/avajs/ava).
- Add example test file
- Add required configuration for running test using ES Modules

### CODE REVIEW

**Comment by static-raccoon** [comment]
This pull request has been mentioned on **Entropic**. There might be relevant details there:

https://discourse.entropic.dev/t/looking-for-help-test-framework-setup-for-ds/266/6

**Review by emkay — APPROVED** [review]
This is good for me. It gets setups a place for people to put tests and gets esm and ts working with ava.

**Comment by zkat** [comment]
Merged! Thanks!!

**Comment by static-raccoon** [comment]
This pull request has been mentioned on **Entropic**. There might be relevant details there:

https://discourse.entropic.dev/t/looking-for-help-test-framework-setup-for-ds/266/7

**Pull request merged**
