### PR TITLE
load esm before node/index.js

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by zkat** [comment]
Did this fix the issue for you?

**Comment by ghost** [comment]
When we load `esm` before it now does not recognize typescript

```
$ node bin/ds.js 
/Users/ysz/oss/ds/bin/ds.js:1
Error [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension: /Users/ysz/oss/ds/src/node/index.ts
    at Object.<anonymous> (/Users/ysz/oss/ds/bin/ds.js:14:1)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:643:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
```

**Comment by zkat** [comment]
This is probably because we're transpiling now and the paths need to bed changed from src to lib

**Comment by zkat** [comment]
I've taken this as a starting point and taken it over the finish line. It's now pushed to `latest`. Thank you!

**Pull request closed without merging**
